harmonoid/harmonoid

lib/scripts/globalsupdater.dart
When I used the localized version of the app, I noticed that some phrases look bad. Sorry for not fixing them in the last PR.
=> Improve Russian translation

lib/scripts/globalsupdater.dart
=> Update of Slovenian language

lib/scripts/globalsupdater.dart
Forgot to translate 2 sentences.
😒
=> Update sl lang

README.md
Just added a few cute sheilds.
Discord invite link: [discord.gg/mRxH9zYkGy](https://discord.gg/mRxH9zYkGy)
=> 😎 Add sheilds & Discord server

lib/language/language.dart
Translated application to dutch using the existing English translation
=> Added Dutch translation

lib/language/language.dart
Update the portuguese language.
=> Update pt-br lang

lib/language/language.dart
Translated the things that weren't translated and changes somethings that felt a bit off
=> Portuguese language update.

lib/language/language.dart, lib/screens/collection/collectionalbum.dart, lib/screens/collection/collectionmusic.dart, lib/screens/collection/collectiontrack.dart, lib/screens/discover/discovermusic.dart, lib/screens/discover/discoversearch.dart, lib/screens/discover/discovertrack.dart, lib/screens/home.dart, lib/screens/nowplaying.dart, lib/screens/settings/about.dart, lib/screens/settings/accent.dart, lib/screens/settings/language.dart, lib/screens/settings/miscellaneous.dart, lib/screens/settings/settings.dart, lib/widgets.dart, pubspec.lock, pubspec.yaml
Created some UI updates. Now the app feels better :)
UI updates and fixes:
- 🦜 Language section in settings can now be collapsed and Language Tiles now have the flag of the country
- 🖇 The name of some songs was being clipped. (TODO: the name of albums and artists are also being clipped)
- 💫 A weird scroll behavior. (TODO: apply the scroll behavior of the fixed listview to the whole app using a `ScrolConfiguration`)
- 👨‍🎤 Ink well wasn't working on the albums section
- 🤳 Ink well didn't include the image
| Before | Now |
| ------- | ----- |
| ![previous_language](https://user-images.githubusercontent.com/45696119/108779657-f6476780-7545-11eb-9d0e-14ee57d343aa.png) | ![now_language](https://user-images.githubusercontent.com/45696119/108780727-981b8400-7547-11eb-9ae7-e99f7ecde1d0.png) | 
| …
=> UI updates

lib/constants/language.dart
I appreciate your work and I I make my part of the contribution
=> Add french langage in the application

lib/constants/language.dart
=> 🇸🇮 Update for SL language & added comments for better visibility of what hasn't been translated yet

lib/constants/language.dart
=> Update pt_br lang

lib/interface/collection/collectionalbum.dart, lib/interface/collection/collectionartist.dart, lib/interface/collection/collectionplaylist.dart, lib/interface/collection/collectiontrack.dart, lib/interface/harmonoid.dart, lib/interface/nowplaying.dart, lib/interface/nowplayingbar.dart, lib/interface/settings/about/aboutpage.dart, lib/interface/settings/about/thirdpartypage.dart, lib/interface/settings/indexing.dart, lib/interface/settings/language.dart, lib/interface/settings/miscellaneous.dart, lib/interface/settings/version.dart, lib/utils/utils.dart, lib/utils/widgets.dart, linux/flutter/generated_plugin_registrant.cc, linux/flutter/generated_plugin_registrant.h, pubspec.lock, windows/flutter/generated_plugin_registrant.cc, windows/flutter/generated_plugin_registrant.h
=> 🚑 Fix deprecated api's / Flutter 2.5

.github/workflows/ci.yml, .gitignore, README.md, linux/debian/harmonoid_0.1.3-1/usr/share/applications/harmonoid.desktop, linux/debian/harmonoid_0.1.3-1/usr/share/metainfo/harmonoid.appdata.xml, pubspec.yaml
Appimage currently doesn't include all the required libraries, so this PR is draft.
=> 🚚 Rename Linux package & add AppImage support

lib/interface/collection/collectionalbum.dart, lib/interface/collection/collectionartist.dart, lib/interface/exception.dart
The artist and album page sidebars were not consistent. One was wider than the other and had borders which looked ugly. Also it had an overflow error on my small screen due to the image being large, so I fixed that too.
=> Fix UI quirks and inconsistencies in collection sidebar

CONTRIBUTING.md
Update contribution guidelines.
=> 📝Update CONTRIBUTING.md

.github/workflows/master.yml
=> Add rpm build

assets/translations/tr_TR.json
Translation updated ✔️
Some syntax errors fixed ✔️
=> Update Turkish translation

lib/core/configuration.dart, lib/utils/widgets.dart
`MoveWindow` and buttons are now separate child elements of `Row`. Plus the `RangeError` has been fixed, which did not allow me to build it.
=> Fix dragging by buttons (#167)

lib/youtube/youtube.dart, pubspec.yaml
Hello 
related to #165 
This PR add **keyboard navigation** and **term highlight** (using [substring_highlight](https://pub.dev/packages/substring_highlight)) to the YouTube search field:
=> Youtube keyboard navigation

lib/core/playback.dart, lib/utils/extensions.dart, lib/youtube/youtube.dart, lib/youtube/youtube_api.dart, lib/youtube/youtube_tile.dart
- bugs fixes and improvements in the youtube tab
- fix a critical bug https://github.com/harmonoid/harmonoid/commit/33575580197468ce358a6c4090d0a23733a2f232#commitcomment-67673995
=> Yehuda main

README.md, assets/translations/az_AZ.json, assets/translations/de_DE.json, assets/translations/en_US.json, assets/translations/fa_IR.json, assets/translations/fr_FR.json, assets/translations/hi_IN.json, assets/translations/hu_HU.json, assets/translations/ja_JP.json, assets/translations/mg_MG.json, assets/translations/nl_NL.json, assets/translations/pt_BR.json, assets/translations/ru_RU.json, assets/translations/sl_SI.json, assets/translations/sv_SE.json, assets/translations/tr_TR.json, assets/translations/zh_CN.json, lib/constants/language.dart, lib/constants/strings.dart, lib/core/app_state.dart, lib/core/collection.dart, lib/interface/settings/about.dart, lib/interface/settings/indexing.dart, lib/main.dart, lib/models/track.dart, lib/state/collection_refresh.dart, lib/utils/file_system.dart, lib/youtube/youtube_api.dart
- Improve `refresh` implementation in `Collection` to be faster.
- Removes `setDirectories` API from `Collection` in favor of more performant `addDirectories` & `removeDirectories`.
- Handles network drives correctly.
- Adds warning `AlertDialog`s for other occasions.
Addresses #219 & #224 (no more critical issue, time for another hot-fix release 🩹🩹🩹).
=> ♻️ Refactor: Indexing & file-system

Harmonoid_InnoSetup.iss
=> fix bug #227

linux/rpm/harmonoid.spec
=> Final Fix for rpm build and #132
